/* The following code was generated by JFlex 1.7.0 */

package ar.edu.unlu.teocomp1.grupo3;

import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexico.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\6\1\0\1\5\23\0\1\3\1\7\1\12\5\0"+
    "\1\15\1\22\1\14\1\55\1\20\1\56\1\11\1\13\1\16\1\17"+
    "\1\21\3\2\1\31\3\2\1\53\1\65\1\57\1\54\1\60\1\7"+
    "\1\0\3\30\1\23\2\30\1\25\1\1\1\24\5\1\1\27\4\1"+
    "\1\26\6\1\1\61\1\0\1\62\1\0\1\10\1\0\1\43\2\30"+
    "\1\40\1\34\1\33\1\52\1\1\1\32\2\1\1\35\1\47\1\37"+
    "\1\50\1\42\1\1\1\41\1\36\1\44\1\45\1\1\1\46\1\51"+
    "\2\1\1\63\1\0\1\64\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\2\1\1\10\1\11\1\12\1\13\1\14\14\2\1\15"+
    "\1\1\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\0\1\30\4\0\1\31\15\2"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\4\0\1\40"+
    "\2\2\1\41\1\42\3\2\1\43\4\2\1\44\3\0"+
    "\1\2\1\45\11\2\1\46\2\0\1\47\1\50\4\2"+
    "\1\51\1\52\2\2\1\53\1\0\1\2\1\54\1\55"+
    "\1\2\1\56\1\57\1\2\1\60\1\2\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\66\0\66\0\66\0\66"+
    "\0\330\0\u010e\0\u0144\0\66\0\u017a\0\66\0\66\0\u01b0"+
    "\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360"+
    "\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\66\0\66\0\u04a4"+
    "\0\u04da\0\66\0\66\0\66\0\66\0\66\0\330\0\u010e"+
    "\0\66\0\u0510\0\u0546\0\u057c\0\u05b2\0\154\0\u05e8\0\u061e"+
    "\0\u0654\0\u068a\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce"+
    "\0\u0804\0\u083a\0\u0870\0\154\0\66\0\66\0\66\0\66"+
    "\0\66\0\u08a6\0\u08dc\0\u0912\0\u0948\0\154\0\u097e\0\u09b4"+
    "\0\u09ea\0\154\0\u0a20\0\u0a56\0\u0a8c\0\154\0\u0ac2\0\u0af8"+
    "\0\u0b2e\0\u0b64\0\66\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\154"+
    "\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec"+
    "\0\u0e22\0\66\0\u0e58\0\u0e8e\0\154\0\154\0\u0ec4\0\u0efa"+
    "\0\u0f30\0\u0f66\0\154\0\154\0\u0f9c\0\u0fd2\0\66\0\u1008"+
    "\0\u103e\0\154\0\154\0\u1074\0\154\0\154\0\u10aa\0\154"+
    "\0\u10e0\0\154";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\2"+
    "\1\11\1\12\1\13\1\14\1\15\2\4\1\16\1\4"+
    "\1\17\6\3\1\4\1\20\1\21\1\22\1\3\1\23"+
    "\1\3\1\24\1\25\1\26\1\27\1\3\1\30\1\31"+
    "\1\32\1\33\2\3\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\67\0\2\3"+
    "\5\0\1\3\5\0\2\3\1\0\1\3\1\0\30\3"+
    "\15\0\1\4\6\0\1\47\4\0\2\4\1\0\1\4"+
    "\7\0\1\4\36\0\1\47\13\0\2\47\1\0\1\47"+
    "\7\0\1\47\35\0\4\50\2\0\2\50\1\0\1\51"+
    "\3\0\2\50\1\0\1\50\1\0\30\50\3\0\1\50"+
    "\23\0\1\52\67\0\2\53\3\0\1\54\4\0\1\55"+
    "\2\0\2\55\3\0\1\55\2\0\1\55\23\0\2\3"+
    "\5\0\1\3\5\0\2\3\1\0\1\3\1\0\10\3"+
    "\1\56\3\3\1\57\13\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\12\3\1\60\15\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\12\3\1\61\1\3\1\62\13\3\14\0\2\3"+
    "\5\0\1\3\5\0\2\3\1\0\1\3\1\0\21\3"+
    "\1\63\6\3\14\0\2\3\5\0\1\3\5\0\2\3"+
    "\1\0\1\3\1\0\11\3\1\64\16\3\14\0\2\3"+
    "\5\0\1\3\5\0\2\3\1\0\1\3\1\0\11\3"+
    "\1\65\16\3\14\0\2\3\5\0\1\3\5\0\2\3"+
    "\1\0\1\3\1\0\16\3\1\66\11\3\14\0\2\3"+
    "\5\0\1\3\5\0\2\3\1\0\1\3\1\0\14\3"+
    "\1\67\13\3\14\0\2\3\5\0\1\3\5\0\2\3"+
    "\1\0\1\3\1\0\14\3\1\70\13\3\14\0\2\3"+
    "\5\0\1\3\5\0\2\3\1\0\1\3\1\0\16\3"+
    "\1\71\11\3\14\0\2\3\5\0\1\3\5\0\2\3"+
    "\1\0\1\3\1\0\7\3\1\72\10\3\1\73\7\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\16\3\1\74\11\3\67\0\1\75\65\0\1\76"+
    "\65\0\1\77\3\0\1\100\61\0\1\101\12\0\4\52"+
    "\1\0\3\52\3\0\1\102\1\0\2\52\1\0\1\52"+
    "\1\0\30\52\3\0\1\52\25\0\2\53\1\103\65\0"+
    "\1\104\2\0\1\54\1\105\3\0\1\55\2\0\2\55"+
    "\3\0\1\55\2\0\1\55\42\0\1\104\2\0\1\54"+
    "\4\0\1\55\2\0\2\55\3\0\1\55\2\0\1\55"+
    "\23\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\21\3\1\106\6\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\25\3\1\107\2\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\13\3\1\110\14\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\15\3\1\111\12\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\16\3\1\112\11\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\10\3\1\113\17\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\17\3\1\114\10\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\25\3\1\115\2\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\15\3\1\116\12\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\21\3\1\117\6\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\7\3\1\120\20\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\14\3\1\121\13\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\26\3\1\122\1\3\26\0\1\123\73\0\1\124"+
    "\63\0\1\125\73\0\1\126\41\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\20\3\1\127\7\3"+
    "\14\0\2\3\5\0\1\3\5\0\2\3\1\0\1\3"+
    "\1\0\11\3\1\130\16\3\14\0\2\3\5\0\1\3"+
    "\5\0\2\3\1\0\1\3\1\0\7\3\1\131\5\3"+
    "\1\132\12\3\14\0\2\3\5\0\1\3\5\0\2\3"+
    "\1\0\1\3\1\0\7\3\1\133\20\3\14\0\2\3"+
    "\5\0\1\3\5\0\2\3\1\0\1\3\1\0\11\3"+
    "\1\134\16\3\14\0\2\3\5\0\1\3\5\0\2\3"+
    "\1\0\1\3\1\0\27\3\1\135\14\0\2\3\5\0"+
    "\1\3\5\0\2\3\1\0\1\3\1\0\7\3\1\136"+
    "\20\3\14\0\2\3\5\0\1\3\5\0\2\3\1\0"+
    "\1\3\1\0\21\3\1\137\6\3\14\0\2\3\5\0"+
    "\1\3\5\0\2\3\1\0\1\3\1\0\7\3\1\140"+
    "\20\3\14\0\2\3\5\0\1\3\5\0\2\3\1\0"+
    "\1\3\1\0\7\3\1\141\20\3\35\0\1\142\74\0"+
    "\1\143\60\0\1\144\42\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\21\3\1\145\6\3\14\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\10\3\1\146\17\3\14\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\11\3\1\147\16\3\14\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\14\3\1\150\13\3\14\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\20\3\1\151\7\3\14\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\16\3\1\152\11\3\14\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\12\3\1\153\15\3\14\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\11\3\1\154\16\3\14\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\24\3\1\155\3\3\14\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\24\3\1\156\3\3\35\0\1\157\71\0\1\160\40\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\10\3\1\161\17\3\14\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\11\3\1\162\16\3\14\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\21\3\1\163\6\3\14\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\20\3\1\164\7\3\14\0"+
    "\2\3\5\0\1\3\5\0\2\3\1\0\1\3\1\0"+
    "\25\3\1\165\2\3\14\0\2\3\5\0\1\3\5\0"+
    "\2\3\1\0\1\3\1\0\25\3\1\166\2\3\42\0"+
    "\1\55\37\0\2\3\5\0\1\3\5\0\2\3\1\0"+
    "\1\3\1\0\7\3\1\167\20\3\14\0\2\3\5\0"+
    "\1\3\5\0\2\3\1\0\1\3\1\0\24\3\1\170"+
    "\3\3\14\0\2\3\5\0\1\3\5\0\2\3\1\0"+
    "\1\3\1\0\14\3\1\171\13\3\14\0\2\3\5\0"+
    "\1\3\5\0\2\3\1\0\1\3\1\0\11\3\1\172"+
    "\16\3\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4374];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\4\11\3\1\1\11\1\1\2\11"+
    "\16\1\2\11\2\1\5\11\1\1\1\0\1\11\4\0"+
    "\17\1\5\11\4\0\15\1\1\11\3\0\13\1\1\11"+
    "\2\0\12\1\1\11\1\0\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private List<Resultado>    resultados = new ArrayList<>();
    
    private void agregarToken(String token){
        resultados.add(new Resultado(token, this.yytext(), this.yyline, this.yycolumn, this.yychar, this.yylength()));
    }

    /*private void agregarError(){
        resultados.add(new Resultado(this.yytext(), this.yyline, this.yycolumn, this.yychar, this.yylength()));
    } */

    public List<Resultado> getResultados() {
        return resultados;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 182) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.printf("ERROR: Lexema: %s | linea %s | Columna %s\n", this.yytext(), this.yyline, this.yycolumn);
            } 
            // fall through
          case 50: break;
          case 2: 
            { agregarToken("ID"); return new Symbol(sym.ID, this.yytext());
            } 
            // fall through
          case 51: break;
          case 3: 
            { if (Integer.parseInt(this.yytext()) < 65536) {
                           agregarToken("CONST_INT");
                           return new Symbol(sym.CONST_INT, this.yytext());
                       } else {
                           System.err.printf ("ERROR: Se encontro int mayor a 16 bits: %s \n", this.yytext());
                       }
            } 
            // fall through
          case 52: break;
          case 4: 
            { System.out.println("espacio");
            } 
            // fall through
          case 53: break;
          case 5: 
            { System.out.println("tab");
            } 
            // fall through
          case 54: break;
          case 6: 
            { System.out.println("FORM_FEED");
            } 
            // fall through
          case 55: break;
          case 7: 
            { System.out.println("ENTER");
            } 
            // fall through
          case 56: break;
          case 8: 
            { agregarToken("OP_DIV"); return new Symbol(sym.OP_DIV, this.yytext());
            } 
            // fall through
          case 57: break;
          case 9: 
            { agregarToken("OP_MULT"); return new Symbol(sym.OP_MULT, this.yytext());
            } 
            // fall through
          case 58: break;
          case 10: 
            { agregarToken("PAREN_ABRIR"); return new Symbol(sym.PAREN_ABRIR, this.yytext());
            } 
            // fall through
          case 59: break;
          case 11: 
            { agregarToken("COMA"); return new Symbol(sym.COMA, this.yytext());
            } 
            // fall through
          case 60: break;
          case 12: 
            { agregarToken("PAREN_CERRAR"); return new Symbol(sym.PAREN_CERRAR, this.yytext());
            } 
            // fall through
          case 61: break;
          case 13: 
            { agregarToken("DOSP"); return new Symbol(sym.DOSP, this.yytext());
            } 
            // fall through
          case 62: break;
          case 14: 
            { agregarToken("OP_SUM"); return new Symbol(sym.OP_SUM, this.yytext());
            } 
            // fall through
          case 63: break;
          case 15: 
            { agregarToken("OP_RESTA"); return new Symbol(sym.OP_RESTA, this.yytext());
            } 
            // fall through
          case 64: break;
          case 16: 
            { agregarToken("OP_LT"); return new Symbol(sym.OP_LT, this.yytext());
            } 
            // fall through
          case 65: break;
          case 17: 
            { agregarToken("OP_GT"); return new Symbol(sym.OP_GT, this.yytext());
            } 
            // fall through
          case 66: break;
          case 18: 
            { agregarToken("LS_ABRIR"); return new Symbol(sym.LS_ABRIR, this.yytext());
            } 
            // fall through
          case 67: break;
          case 19: 
            { agregarToken("LS_CERRAR"); return new Symbol(sym.LS_CERRAR, this.yytext());
            } 
            // fall through
          case 68: break;
          case 20: 
            { agregarToken("BL_ABRIR"); return new Symbol(sym.BL_ABRIR, this.yytext());
            } 
            // fall through
          case 69: break;
          case 21: 
            { agregarToken("BL_CERRAR"); return new Symbol(sym.BL_CERRAR, this.yytext());
            } 
            // fall through
          case 70: break;
          case 22: 
            { agregarToken("PYC"); return new Symbol(sym.PYC, this.yytext());
            } 
            // fall through
          case 71: break;
          case 23: 
            { try {
                           Float.parseFloat(this.yytext());
                           agregarToken("CONST_FLOAT");
                           return new Symbol(sym.CONST_FLOAT, this.yytext());
                       } catch (NumberFormatException e){ 
                           System.err.printf ("ERROR: Se encontro float invalido: %s \n", this.yytext());
                       }
            } 
            // fall through
          case 72: break;
          case 24: 
            { if (this.yylength() <= 32) {
                           agregarToken("CONST_STRING");
                           return new Symbol(sym.CONST_STRING, this.yytext());
                       } else {
                           System.err.printf ("ERROR: Se encontro string con %s caracteres \n", this.yylength()-2);
                       }
            } 
            // fall through
          case 73: break;
          case 25: 
            { agregarToken("PR_IF"); return new Symbol(sym.PR_IF, this.yytext());
            } 
            // fall through
          case 74: break;
          case 26: 
            { agregarToken("PR_OR"); return new Symbol(sym.PR_OR, this.yytext());
            } 
            // fall through
          case 75: break;
          case 27: 
            { agregarToken("ASSIGN"); return new Symbol(sym.ASSIGN, this.yytext());
            } 
            // fall through
          case 76: break;
          case 28: 
            { agregarToken("OP_EQ"); return new Symbol(sym.OP_EQ, this.yytext());
            } 
            // fall through
          case 77: break;
          case 29: 
            { agregarToken("OP_LE"); return new Symbol(sym.OP_LE, this.yytext());
            } 
            // fall through
          case 78: break;
          case 30: 
            { agregarToken("OP_DIFF"); return new Symbol(sym.OP_DIFF, this.yytext());
            } 
            // fall through
          case 79: break;
          case 31: 
            { agregarToken("OP_GE"); return new Symbol(sym.OP_GE, this.yytext());
            } 
            // fall through
          case 80: break;
          case 32: 
            { agregarToken("PR_INT"); return new Symbol(sym.PR_INT, this.yytext());
            } 
            // fall through
          case 81: break;
          case 33: 
            { agregarToken("PR_END"); return new Symbol(sym.PR_END, this.yytext());
            } 
            // fall through
          case 82: break;
          case 34: 
            { agregarToken("PR_STR"); return new Symbol(sym.PR_STR, this.yytext());
            } 
            // fall through
          case 83: break;
          case 35: 
            { agregarToken("PR_AND"); return new Symbol(sym.PR_AND, this.yytext());
            } 
            // fall through
          case 84: break;
          case 36: 
            { System.out.println("COMMENT");
            } 
            // fall through
          case 85: break;
          case 37: 
            { agregarToken("PR_ELSE"); return new Symbol(sym.PR_ELSE, this.yytext());
            } 
            // fall through
          case 86: break;
          case 38: 
            { agregarToken("CONST_BIN"); return new Symbol(sym.CONST_BIN, this.yytext());
            } 
            // fall through
          case 87: break;
          case 39: 
            { agregarToken("PR_FLOAT"); return new Symbol(sym.PR_FLOAT, this.yytext());
            } 
            // fall through
          case 88: break;
          case 40: 
            { agregarToken("PR_ENDIF"); return new Symbol(sym.PR_ENDIF, this.yytext());
            } 
            // fall through
          case 89: break;
          case 41: 
            { agregarToken("PR_UNTIL"); return new Symbol(sym.PR_UNTIL, this.yytext());
            } 
            // fall through
          case 90: break;
          case 42: 
            { agregarToken("PR_WRITE"); return new Symbol(sym.PR_WRITE, this.yytext());
            } 
            // fall through
          case 91: break;
          case 43: 
            { agregarToken("CONST_HEX"); return new Symbol(sym.CONST_HEX, this.yytext());
            } 
            // fall through
          case 92: break;
          case 44: 
            { agregarToken("PR_DEFINE"); return new Symbol(sym.PR_DEFINE, this.yytext());
            } 
            // fall through
          case 93: break;
          case 45: 
            { agregarToken("PR_REPEAT"); return new Symbol(sym.PR_REPEAT, this.yytext());
            } 
            // fall through
          case 94: break;
          case 46: 
            { agregarToken("PR_MINIMO"); return new Symbol(sym.PR_MINIMO, this.yytext());
            } 
            // fall through
          case 95: break;
          case 47: 
            { agregarToken("PR_MAXIMO"); return new Symbol(sym.PR_MAXIMO, this.yytext());
            } 
            // fall through
          case 96: break;
          case 48: 
            { agregarToken("PR_PROGRAM"); return new Symbol(sym.PR_PROGRAM, this.yytext());
            } 
            // fall through
          case 97: break;
          case 49: 
            { agregarToken("PR_ENDDEFINE"); return new Symbol(sym.PR_ENDDEFINE, this.yytext());
            } 
            // fall through
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
