
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ar.edu.unlu.teocomp1.grupo3;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAREN_CERRAR = 41;
  public static final int PR_DEFINE = 10;
  public static final int PR_INT = 16;
  public static final int BL_CERRAR = 39;
  public static final int PR_MINIMO = 8;
  public static final int PAREN_ABRIR = 40;
  public static final int PR_OR = 15;
  public static final int PR_AND = 14;
  public static final int OP_GT = 32;
  public static final int PR_ENDIF = 4;
  public static final int PR_IF = 2;
  public static final int PR_ELSE = 3;
  public static final int OP_DIV = 29;
  public static final int PR_FLOAT = 18;
  public static final int LS_ABRIR = 36;
  public static final int OP_GE = 34;
  public static final int OP_DIFF = 30;
  public static final int PR_MAXIMO = 9;
  public static final int CONST_FLOAT = 22;
  public static final int ASSIGN = 25;
  public static final int ID = 19;
  public static final int PR_PROGRAM = 12;
  public static final int EOF = 0;
  public static final int CONST_BIN = 23;
  public static final int BL_ABRIR = 38;
  public static final int error = 1;
  public static final int OP_LT = 31;
  public static final int COMA = 42;
  public static final int OP_MULT = 28;
  public static final int OP_RESTA = 27;
  public static final int PR_ENDDEFINE = 11;
  public static final int PR_END = 13;
  public static final int OP_LE = 33;
  public static final int OP_SUM = 26;
  public static final int PR_WRITE = 7;
  public static final int CONST_STRING = 20;
  public static final int DOSP = 43;
  public static final int OP_EQ = 35;
  public static final int LS_CERRAR = 37;
  public static final int PR_UNTIL = 6;
  public static final int PR_REPEAT = 5;
  public static final int PR_STR = 17;
  public static final int PYC = 44;
  public static final int CONST_INT = 21;
  public static final int CONST_HEX = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_IF",
  "PR_ELSE",
  "PR_ENDIF",
  "PR_REPEAT",
  "PR_UNTIL",
  "PR_WRITE",
  "PR_MINIMO",
  "PR_MAXIMO",
  "PR_DEFINE",
  "PR_ENDDEFINE",
  "PR_PROGRAM",
  "PR_END",
  "PR_AND",
  "PR_OR",
  "PR_INT",
  "PR_STR",
  "PR_FLOAT",
  "ID",
  "CONST_STRING",
  "CONST_INT",
  "CONST_FLOAT",
  "CONST_BIN",
  "CONST_HEX",
  "ASSIGN",
  "OP_SUM",
  "OP_RESTA",
  "OP_MULT",
  "OP_DIV",
  "OP_DIFF",
  "OP_LT",
  "OP_GT",
  "OP_LE",
  "OP_GE",
  "OP_EQ",
  "LS_ABRIR",
  "LS_CERRAR",
  "BL_ABRIR",
  "BL_CERRAR",
  "PAREN_ABRIR",
  "PAREN_CERRAR",
  "COMA",
  "DOSP",
  "PYC"
  };
}

